import classes from "./Main.module.css";
import logo from "../../images/logo.png";

const Main = ()=> {
    return(
        <main className={`bg_container ${classes.main}`}>
         <img src={logo} />
         <h4>Your Account</h4>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>
         <p>Message</p>

        </main>
    )
}
export default Main;